# deploy config
port: 8891
infer_weights: ./runs/detect/train3/weights/best.pt

# training config
dataset: /home/dataset/dataset.yaml
model: ./model/yolov8m.yaml
training_weights: ./runs/detect/train3/weights/best.pt
